spring:
  application:
    name: food.flix
  datasource:
    url: jdbc:postgresql://localhost:5432/foodflix?ApplicationName=food.flix
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
      idle-timeout: 20000
      poolName: food.flix